// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkehwyimfzbefiukyfem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZWh3eWltZnpiZWZpdWt5ZmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODI3NTksImV4cCI6MjA3MjU1ODc1OX0.KhMbfXieoXnp-X_Eu4B_akZiG-nMeTPr9BClk81jdQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});